language: perl
sudo: false

install:
  - perlbrew list
  - cpanm -n Alien::FFCall ExtUtils::MakeMaker
  - cpanm --installdeps -n -v .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - perl Makefile.PL
  - make
  - prove -bv
